### PR TITLE
feat(automod): MIME type trigger

### PR DESCRIPTION
**Pull request by ghost**
Hello Dark,
Using the attachment type trigger as a reference, I've completed the new automod trigger which checks the MIME types of files. I haven't tested it, but if you need to me to I can. Feel free to request any changes and I'll get back to them as soon as possible.
_As requested by @Dragory, I've opened my pull request to be merged into your `djs` branch._

### CODE REVIEW

**Comment by DarkView** [comment]
Yes, please test these changes as I am quite busy testing the rest of my changes :D

Also the lockfile was not corrupted, I am just using Nodev16 for development here which comes with NPMv7.
The new NPM version uses lockFileVersion 2 instead of 1, but is [fully compatible with version 1](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion). It just includes more info. 

Thanks for the PR already, I will merge it soon if you can test it. If not, I will merge and test it after I'm done with the rest of the changes.

**Comment by ghost** [comment]
Starting another Zeppelin instance is just a pain, that's all. Are your Discord.js changes complete as yet?

**Comment by DarkView** [comment]
I don't intend on adding any new "major" features.
But there are still a few PRs open for DJS and I need to bugtest just about everything.

**Comment by ghost** [comment]
Alright, well please let me know when you've tested your changes. I'll merge our changes to my production instance of Zeppelin and test them there.

**Comment by DarkView** [comment]
On another note you should probably add checks for the whitelist and blacklist.
Need to make sure that only the blacklist *or* the whitelist is enabled and that one is enabled in the first place.
You can probably just copy [this block](https://github.com/DarkView/ZeppelinBot/blob/a9e0466e33b0a102322ac041bfe28b66bf904cbb/backend/src/plugins/Automod/AutomodPlugin.ts#L102) for that.

**Comment by DarkView** [comment]
The changes are tested as much as we can, and my base PR was properly reviewed by @almeidx.
Please test your changes and upgrade to NPMv7 so the lockfile stays at version 2.

I will let Dragory know that the base PR can be merged as soon as he has proper time though, so it would be ideal if you could test this quickly. Otherwise you might need to change the PR again to target the proper repository.

**Comment by ghost** [comment]
Alright, I understand. About the package-lock.json, I'm not sure if I can do that. NPM throws errors when I use v7. v6.14.13 works without issues though.

**Comment by DarkView** [comment]
> Alright, I understand. About the package-lock.json, I'm not sure if I can do that. NPM throws errors when I use v7. v6.14.13 works without issues though.

Feel free to DM me on Discord so we can take a look at the errors. Dark#1010

**Comment by ghost** [comment]
> On another note you should probably add checks for the whitelist and blacklist.
> Need to make sure that only the blacklist _or_ the whitelist is enabled and that one is enabled in the first place.
> You can probably just copy [this block](https://github.com/DarkView/ZeppelinBot/blob/a9e0466e33b0a102322ac041bfe28b66bf904cbb/backend/src/plugins/Automod/AutomodPlugin.ts#L102) for that.

Implemented in https://github.com/DarkView/ZeppelinBot/pull/1/commits/774cfb321e2bfbb07764a70bbce8796391f91fad.

**Comment by ghost** [comment]
I'll merge my changes over to my primary fork at [TeamRubellite/ZeppelinBot](https://github.com/TeamRubellite/ZeppelinBot). Once there, I can finalize this trigger by testing my changes.

**Comment by ghost** [comment]
Alright, I've tested it. Seems good to go! Just a note, some types (unrelated to my feature) are broken and logging is broken for automod actions.

**Review by shoaibsajid1 — APPROVED** [review]

**Comment by ghost** [comment]
Alright Dark, as requested, I've updated the attachment handling. It now uses the `contentType` property (https://discord.com/developers/docs/resources/channel#attachment-object) instead of fetching and downloading the file as a buffer, then to find the MIME type.

**Comment by DarkView** [comment]
Your PR is still reverting a package-lock file to version 1.
Please re-generate it using npm7 (which is included in node16, which djs13 requires).

**Comment by ghost** [comment]
I have version 2 of the package-lock.json file though. https://github.com/WeebHiroyuki/ZeppelinBot/blob/feat/mime-checking/backend/package-lock.json#L4

**Comment by DarkView** [comment]
In the `backend` folder, yes.
Though not in the root folder :D 
https://github.com/WeebHiroyuki/ZeppelinBot/blob/feat/mime-checking/package-lock.json

**Comment by ghost** [comment]
I'm closing to reopen on the root repository ([Dragory/ZeppelinBot](https://github.com/Dragory/ZeppelinBot)). Apologies for not completing the requested changes in time before the merge.

**Pull request closed without merging**
